[package]
name = "lunabot"
version = "0.1.0"
edition = "2021"

[dependencies]
urobotics = { workspace = true, features = [
    "serial",
    "camera",
    "python",
    "app",
    "video",
] }
serde = { workspace = true }
spin_sleep = { workspace = true }
cakap2 = { workspace = true }
anyhow = { workspace = true }
crossbeam = { workspace = true }
compute-shader = { workspace = true }
common = { path = "../common" }
pathfinding = { path = "../pathfinding" }
nalgebra = { workspace = true }
k = { workspace = true }
# indexmap = "2.2.6"
fxhash = { workspace = true }
vesc-translator = { workspace = true }
fitter = { workspace = true }
recycler = { workspace = true }
bitcode = { workspace = true }
heightmap = { path = "../heightmap" }
lunabot-ai = { path = "../lunabot-ai" }
tokio-serial = "5"